[package]
name = "bin"
version.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pjsekai-soundgen"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono = "0.4.31"
console = "0.15.7"
dialoguer = "0.10.1"
dirs.workspace = true
enable-ansi-support = "0.1.2"
getopts = "0.2.21"
indicatif = "0.16.2"
octocrab = "0.32.0"
once_cell = "1.13.0"
pjsekai-soundgen-core.workspace = true
process_path = "0.1.4"
regex.workspace = true
tokio = { version = "1.28.2", features = ["full"] }
